### ISSUE TITLE
Questions about this project

### ISSUE THREAD

**Issue by MauriceWebb** [borisno2/on-the-hill-drama-club#118]
Hello, I came across this project by viewing your short series on Youtube describing what you referred to as "[serverless keystone](https://www.youtube.com/watch?v=Wq6eQVyW8ug)". 

I absolutely love the Keystone project but not having a serverless option for the Admin UI makes it difficult to use for clients. 

Can you elaborate more about the build and deploy steps?

- bulding and deploying the frontend (Nextjs app with Keystone's `getContext` API to say, Vercel)
- building and deploying Keystone's Admin UI as a standalone server
- with the frontend and admin UI using rewrites

I've been trying to deploy them to AWS but I believe I am missing steps. Would be nice to have a straightforward tutorial on the above mentioned.

Good stuff, and thank you for open sourcing this project!

**Comment by mstfash** [comment]
Hey Great job open sourcing this, it is really cool!

I have got an issue trying this locally, added some env variables to help running everything and changed the database url and everything however, my sole issue here is I get I go to `http://localhost:4000/admin`, I get 
```
Unhandled Runtime Error
Error: An error occurred when loading Admin Metadata
```

Here is a screenshot that shows the error, tried visiting keystone github repo but had no chance solving this issue.

Have you ever faced this issue? or could you help me out try to figure out what is going on ? Thanks in advance and again great work!

![Screen Shot 2023-07-19 at 6 18 57 AM](https://github.com/borisno2/on-the-hill-drama-club/assets/5751607/33d45e93-a902-4bb8-87e3-14ad5bf8a36d)

**Comment by borisno2** [comment]
Hi @MauriceWebb 

Have you watched the 2nd video in that series https://www.youtube.com/watch?v=B7Gb6cDfCHY that hopefully answers some of your questions. There is a small change as Keystone now supports the `basePath` configuration.

Let me know how you go.

**Comment by MauriceWebb** [comment]
I watched all 3 videos in the series multiple times but what was in the video and what is in the repo differs. I'm trying to make a starter for a serverless keystonejs + nextjs project. Something barebones without auth and multiple lists. Keep getting a 4XX error. Can you write an updated list of what is needed? 

In your video, you deployed:
- keystone admin ui with graphql to vercel
- the on-the-hill-drama-club site to vercel

I saw you "embedded" keystone into your site by:
1. using vercel zones, adding rewrites to your site's next-config that point to your deployed keystone admin endpoint
2. using keystone's context API to CRUD your data

I'm not able to get `1.` to work as expected. When I deploy the keystone app, I run into 4xx errors

1. KeyStone Express server for Admin UI graphql requests
2. Admin UI nextjs app
3. My nextjs app

**Comment by borisno2** [comment]
No worries @MauriceWebb 
A very cutdown version of this is available in the keystone examples here https://github.com/keystonejs/keystone/tree/main/examples/framework-nextjs-app-directory.

Then Admin UI is a Next App that gets generated in `./.keystone/admin` you then need to make sure this app and the frontend app, which contains the grapnel api, are on the same domain so that for example the adminUI is at `https://www.example.com/admin` and the GraphQL api is at `https://www.example.com/api/graphql` - that way the Keystone Admin UI will use the GraphQL of the frontend app.
