### ISSUE TITLE
Not an issue its more kinda favor

### ISSUE THREAD

**Issue by mstfash** [borisno2/on-the-hill-drama-club#159]
Hey great work as usual, I have been working with your files and they are great in every aspect.

What I am trying to build for my company now is kinda the same but they want it to be deployed on AWS do you have any idea how to accomplish the same thing on AWS using turborepo ?

thanks in advance!

**Comment by borisno2** [comment]
Hey @mstfash thanks for reaching out. This question might be better as a discussion in the keystone repo - https://github.com/keystonejs/keystone/discussions - there might even be some discussions that are relevant to you there.
