### ISSUE TITLE
Error: An error occurred when loading Admin Metadata

### ISSUE THREAD

**Issue by sebacura** [borisno2/on-the-hill-drama-club#160]
Hi! I got that error when starting Keystone and accessing /admin, any ideas?

<img width="982" alt="Screenshot 2023-09-06 at 20 29 31" src="https://github.com/borisno2/on-the-hill-drama-club/assets/45567129/7ac5d45b-df79-431b-bdb6-3749c7b89dcf">

**Comment by borisno2** [comment]
Hello @sebacura have a look at #120 - most likely the same issue
